In [28]:
import pandas as pd

In [29]:
info = {
    "name": ["Rahul","harshita","aprajita"],
    "CGPA":[9.8, 8.8, 10]
}

df = pd.DataFrame(info)
print(df)
df

       name  CGPA
0     Rahul   9.8
1  harshita   8.8
2  aprajita  10.0

       name  CGPA
0     Rahul   9.8
1  harshita   8.8
2  aprajita  10.0

In [30]:
# Series
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

# Index 
print(s[1])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
2
3

In [31]:
# Labelling in Series

s = pd.Series([20, 18, 26, 40], index = ["Harsh", "Rohit", "Poonam", "Usha"])
# print(s[0])
print(s.index)

Index(['Harsh', 'Rohit', 'Poonam', 'Usha'], dtype='object')

In [32]:
# Vectorized Operation:-
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)

# Mutuable values
s1[0] = 87
print(s1)

changed_s1 = s1.drop(0)
print(changed_s1)
print(s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    87
1     2
2     3
3     4
4     5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64
0    87
1     2
2     3
3     4
4     5
dtype: int64

In [33]:
# DataFrame
info = {
    "name" : ["Adam", "Eve", "Bob"],
    "age" : [23, 35, 20],
    "GPA" : [9.5, 8.6, 7.2]
}

df = pd.DataFrame(info)
print(df.index)
print(df.columns)
df

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'GPA'], dtype='object')

   name  age  GPA
0  Adam   23  9.5
1   Eve   35  8.6
2   Bob   20  7.2

In [37]:
# Lists of list
df = pd.DataFrame([["Adam",28], ["Bob",20], ["Eve", 40]],columns = ["Name", "Age"])
df

   Name  Age
0  Adam   28
1   Bob   20
2   Eve   40

In [38]:
# DataFrame from numoy arrays
import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6

In [39]:
# CSV Data
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   35000
9  10    Julia   30    Finance   48000 <class 'pandas.core.frame.DataFrame'>

In [40]:
# Json DATA
df = pd.read_json("employee_data.json")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   35000
9  10    Julia   30    Finance   48000

In [54]:
# Methods
df.head()  #Starting 5 rows
df.tail(2)  #Last rows Print karta hai
df.sample()  #Random row print ho jati hai
df.info()  #Summary of our data
df.shape  #Returns a tuple of row and column value (tuples are immutable just like string)
df.describe()  #Returns important statistics of our numerical data
df.columns
df.nunique()  #number of unique data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary         9
dtype: int64